### ISSUE TITLE
Add recaptcha on contact form on CMS page

### ISSUE THREAD

**Issue by tyborr** [magespecialist/m2-MSP_ReCaptcha#10]
Hello

I've implemented your module and it works great, thanks for your hard work on it!

I would like to ask whether it is possible to add reCaptcha on contact form displayed on cms page as an external block. I was trying to make it work via custom layout update, but no success yet.

Thanks in advance

**Comment by phoenix128** [comment]
Can you share with us the custom you made to your layout untill now?
Can you see the recaptcha on the page?

**Comment by tyborr** [comment]
ReCaptcha is working great on contact us default page (/contact), but when I try to add it to contact form on CMS page it doesn't render (for example /about-us), there isn't even a "msp-recaptcha-container" rendered. I tried calling it directly in custom form_aboutus.phtml using:
> echo $this->getLayout()->createBlock('MSP\ReCaptcha\Block\Frontend\ReCaptcha')->setTemplate('MSP_ReCaptcha::msp_recaptcha.phtml')->toHtml();

but this only renders the container, the x-magento-init below it is empty (no return from $block->getJsLayout()).

I've also tried using <update handle="msp_recaptcha" /> in custom layout update for CMS page, but this doesn't do anything.

I've checked that I have 
><?php echo $block->getChildHtml('form.additional.info'); ?>
in my custom form template.
msp_recaptcha.css is added in header on content page,

**Comment by phoenix128** [comment]
Where do you submit your contact information? Are you sending a post to the standard controller?

P.S:
You should include reCaptcha block via layout XML, including it via PH is not the best practice.

**Comment by tyborr** [comment]
Yes, I'm sending it to the standard controller.

**Comment by phoenix128** [comment]
If you see the reCaptcha on your custom form page and you are sendind to the default controller, then it should work.

Do you get any error?

**Comment by tyborr** [comment]
I don't see reCaptcha on my custom form. If I use
>echo $this->getLayout()->createBlock('MSP\ReCaptcha\Block\Frontend\ReCaptcha')->setTemplate('MSP_ReCaptcha::msp_recaptcha.phtml')->toHtml();

in my custom form phtml then it renders only the container
><div class="field-recaptcha" id="msp-recaptcha-container" data-bind="scope:'msp-recaptcha'">
    
</div>

and empty x-magento-init below it:

>{
    "#msp-recaptcha-container": {
        "Magento_Ui/js/core/app": ""
    }

If I remove the createBlock() call from phtml file and leave only:
>getChildHtml('form.additional.info');
Then the captcha block is not rendered. However, the captcha.css is attached in header.

**Comment by phoenix128** [comment]
In your custom phtml try:

```
...
{
  "#msp-recaptcha-container": {
  "Magento_Ui/js/core/app": {
    "components": {
      "msp-recaptcha": {
          "component": "MSP_ReCaptcha\/js\/reCaptcha",
          "zone": "contact"
      }
    }
  }
}
...
```

**Comment by tyborr** [comment]
I need to have manual call of the block in phtml file
>echo $this->getLayout()->createBlock('MSP\ReCaptcha\Block\Frontend\ReCaptcha')->setTemplate('MSP_ReCaptcha::msp_recaptcha.phtml')->toHtml();
but works like a charm. Thanks!

**Comment by phoenix128** [comment]
I'm sorry, I did not explain my solution in details:

In your custom PHTML file, instead of calling:

`echo $this->getLayout()->createBlock('MSP\ReCaptcha\Block\Frontend\ReCaptcha')->setTemplate('MSP_ReCaptcha::msp_recaptcha.phtml')->toHtml();`

Write this:

```
<div class="field-recaptcha" id="msp-recaptcha-container" data-bind="scope:'msp-recaptcha'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "#msp-recaptcha-container": {
        "Magento_Ui/js/core/app": {
          "components": {
            "msp-recaptcha": {"component": "MSP_ReCaptcha\/js\/reCaptcha", "zone": "contact"}
          }
        }
    }
}
</script>
```

**Comment by tyborr** [comment]
Got it. Thanks! Appreciated.

**Comment by phoenix128** [comment]
Does it work as expected? I am considering to add this to our wiki.

**Comment by tyborr** [comment]
Mostly works as supposed to - checking "recaptcha" sends an email correctly, however, when recaptcha is not checked or is invalid it returns to default contact-us page with error message, not to the page from where the form would have been submitted.

**Comment by phoenix128** [comment]
This should be easy to fix:
Check `MSP\ReCaptcha\Observer\Frontend\ContactFormObserver::execute` .

**Comment by tyborr** [comment]
Yes, indeed. Had to add

> use Magento\Framework\App\Response\RedirectInterface;

then

```
public function __construct(
        ValidateInterface $validate,
        Config $config,
        ManagerInterface $messageManager,
        ActionFlag $actionFlag,
        UrlInterface $url,
        RedirectInterface $redirect
    ) {
        $this->validate = $validate;
        $this->config = $config;
        $this->messageManager = $messageManager;
        $this->actionFlag = $actionFlag;
        $this->url = $url;
        $this->redirect = $redirect;
    }
```

and as last thing I've modified creating $url to:
<code>
 $url = $this->url->getUrl($this->redirect->getRedirectUrl());
</code>

And now it all works as expected. Once again thanks!

**Comment by dmarkos** [comment]
I am facing a similar problem. You mentioned a wiki, is it available for public viewing?
