### ISSUE TITLE
Add new v0.1.5 release

### ISSUE THREAD

**Issue by springimport** [magespecialist/m2-MSP_ReCaptcha#2]

**Comment by phoenix128** [comment]
Can you plase provide a description of your issue report?

**Comment by springimport** [comment]
@phoenix128 I want to update my composer with all changes in reCaptcha.
Currently I set `"msp/recaptcha": "dev-master"`. But will be better with version instead `dev-master`.

**Comment by slackerzz** [comment]
We've just tagged a new release.
