### ISSUE TITLE
Plugin breaks tiny_mce in admin panel

### ISSUE THREAD

**Issue by maqlec** [magespecialist/m2-MSP_ReCaptcha#21]
Install the plugin with JS minification enabled cause tiny_mce in admin panel not working.

### Preconditions

1. Magento 2.1.10 or 2.2.2
2. PHP 7

### Steps to reproduce

1. Enabled JS minification in Magento admin panel
2. Generate minified static content
3. Go to product edit and try change field with tiny_mce

### Expected result

1. I could change description using tiny_mce

### Actual result

1. Tiny MCe not working (not loading). There are errors about not existing tiny_mce file in browser console. Browser is looking for not minified tine_mce library files

Problem is in dev/js/minify_exclude setting. Your plugin overrides this setting to google.com and gstatic.com values instead of /tine_mce/ value because tiny_mce library file shouldn't be minified.

**Comment by slackerzz** [comment]
Hi @maqlec, can you please share the all the errors you have in the browser console?

**Comment by maqlec** [comment]
There are simple 404's on loading tiny_mce library JavaScripts. It happens because these files arent excluded from minification.
https://github.com/magespecialist/m2-MSP_ReCaptcha/blob/master/etc/config.xml#L43
These lines are responsible for this action. It overrides excluding setting instead joining new values to original value.

**Comment by slackerzz** [comment]
In my dev installation with magento 2.1.10 tiny_mce comes from magento `static` files, not from google.
I asked you to paste the console errors to see the exact path of the file giving 404 as response.

**Comment by slackerzz** [comment]
Ok, i think i got it

**Comment by maqlec** [comment]
Extra, I forgot to mention that magento should be in production mode to minify assets but Im glad you got it

**Comment by magefan** [comment]
We have the same issue. Any update?

**Comment by slackerzz** [comment]
Hi guys, sorry for the delay. I've just released 1.4.1 with a fix to this minification issue.

**Comment by magefan** [comment]
@slackerzz, thank you for the fix. It works for us on Magento 2.2.2. :+1:

**Comment by maqlec** [comment]
Could you bump msp/security-suite with new version ?

**Comment by slackerzz** [comment]
@maqlec done, msp/security-suite bumped to 2.1.3
