### ISSUE TITLE
Cannot find the module in backend after installation

### ISSUE THREAD

**Issue by Nolwennig** [magespecialist/m2-MSP_ReCaptcha#24]
Hi,

The module work fine on localhost, but doesn 't work on production server. The backend menu doesn't appear and the captcha on frontend forms doesn't appear too.

Any help?

Thanks

### Preconditions
1. Magento 2.1.2 
2. PHP 7.0.27

### Steps to reproduce
1. `composer require msp/recaptcha`
2. `php bin/magento setup:upgrade`

### Expected result
1. Show configuration menu in backend

### Actual result
1. Nothing appaear in backend

**Comment by phoenix128** [comment]
Hello @Nolwennig ,
can you please check if you can see your moduile enabled in `app/etc/config.php` file ?

**Comment by Nolwennig** [comment]
Hello @phoenix128 ,

thank you for your quick response.

Sure, I check now .... (Oh ... I'm so confused .... this check was so obvious).

Finally, the modules `MSP_SecuritySuiteCommon` and `MSP_ReCaptcha` are disable in `app/etc/config.php`

I enabled the modules `MSP_SecuritySuiteCommon` and `MSP_ReCaptcha` (in this order) and now it works perfectly.

Thanks a lot
la vita è bella ;-)
