### ISSUE TITLE
reCaptcha always invalid

### ISSUE THREAD

**Issue by britbarn** [magespecialist/m2-MSP_ReCaptcha#25]
### Preconditions

1. Magento 2.2.1

### Steps to reproduce

1. Composer install package
2. Enable in back end
3. Try to log in as customer

### Expected result

1. Customer logs in

### Actual result

1. says "invalid recaptcha" every time

**Comment by phoenix128** [comment]
Hello @britbarn ,
what kind of reCaptcah rea you using? Standard or invisible?
Are your API registered for your domain?
