### ISSUE TITLE
bug Recaptcha on form account page

### ISSUE THREAD

**Issue by strauss69400** [magespecialist/m2-MSP_ReCaptcha#3]
Hi,
My website running with the version 2.1.6 of Magento.

After installation and configuration of module, theRecaptcha work in Admin but in frontend i get this problem such as describe in the screenshot :
![image](https://cloud.githubusercontent.com/assets/8798254/26676807/a065f088-46c9-11e7-8437-e91ae4700ceb.png)

Do you have any idea of how to resolve the problem?
Thanks
Best regards

**Comment by phoenix128** [comment]
It seems a CSS issue, any problem with default theme? Anyway we did not test it with 2.1.
6 yet.
We will install a dev environment and try to reproduce it.

**Comment by strauss69400** [comment]
I just saw that I also have js errors

![image](https://cloud.githubusercontent.com/assets/8798254/26684653/cf1aed3e-46e7-11e7-9342-04f4961ab9d4.png)

**Comment by phoenix128** [comment]
Problem seems to come from your theme and not module related.
You should let your Magento developers to have a look on it.
