### ISSUE TITLE
Magento 2.1.9 - HTTP Error 500

### ISSUE THREAD

**Issue by rvilama97** [magespecialist/m2-MSP_ReCaptcha#32]
I have added the extension, and all works fine inside the backend and in the frontend it appears fine.

The only code I modified is the system.xml in order to get a tab in the backend.

What happens now is that any time I enable the extension and I try to use the captcha, the webpage crashes after using it, as you can see:

[![enter image description here][1]][1]

Even though before it appears with a green tick:

[![enter image description here][2]][2]

Now, what they say where you get the keys from is this:

[![enter image description here][3]][3]

I got to paste two snippets somewhere in the code, but the thing is atleast as far as I saw, there isn't any code with any tags:

    <head></head>

or:

    <form></form>

All this happens everywhere I place the reCaptcha.

So, **the questions are:**

 1. Where do I have to add those snippets?
 2. Has anyone faced that problem? 
 3. How can I fix it?

  [1]: https://i.stack.imgur.com/CiZ1i.png
  [2]: https://i.stack.imgur.com/ujRDh.png
  [3]: https://i.stack.imgur.com/7zpJr.png

**Comment by giacmir** [comment]
Hi @rvilama97 

When your site crashes you should have some kind of error logged in your server error.log. Can you please post the error stack trace that you can find there?

And for the questions:
1. you don't have to put those snippet anywhere. Just enter your site key in the configuration panel.
2. no
3. please post your error log entry.

**Comment by rvilama97** [comment]
Hi @giacmir, thank you for your time;

I have searched in Magento logs, which I have access to and I only have these ones:

![image](https://user-images.githubusercontent.com/39625379/42692366-c964bca8-86ab-11e8-954e-b4e494c40e18.png)

I imagine I will have to ask for this log to the guys that run the server for us. Can you confirm it? I just want to make sure it's not something else inside Magento that you might need so I can avoid taking their time.

**Comment by giacmir** [comment]
You can look into excepion.log, but usually those 500 errors are printed elsewhere in the server. So, yes, you probably should ask your server admin for that.

**Comment by rvilama97** [comment]
Here we go, this is the error I got:


The error 500 comes from here -> POST /es/customer/account/createpost/ HTTP/1.1


AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Class 'ReCaptcha\\ReCaptcha' not found in /var/www/vhosts/b2b.sap-magento.es/b2b.sap-magento/app/code/MSP/ReCaptcha/Model/Validate.php:55\nStack trace:\n#0 /var/www/vhosts/b2b.sap-magento.es/b2b.sap-magento/app/code/MSP/ReCaptcha/Observer/ReCaptchaObserver.php(93): MSP\\ReCaptcha\\Model\\Validate->validate('03AEMEkEmeATGNV...', '81.47.174.144')\n#1 /var/www/vhosts/b2b.sap-magento.es/b2b.sap-magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): MSP\\ReCaptcha\\Observer\\ReCaptchaObserver->execute(Object(Magento\\Framework\\Event\\Observer))\n#2 /var/www/vhosts/b2b.sap-magento.es/b2b.sap-magento/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(MSP\\ReCaptcha\\Observer\\ReCaptchaObserver), Object(Magento\\Framework\\Event\\Observer))\n#3 /var/www/vhosts/b2b.sap-magento.es/b2b.sap-magento/vendor/magento/framework/Event/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefau...\n', referer: http://b2b.sap-magento.es/es/customer/account/create/

Do you need something else?

**Comment by phoenix128** [comment]
Seems like you did not install it using the **composer** procedure. Please check the readme file.

**Comment by rvilama97** [comment]
Hi @giacmir , 

if I install through composer, vendor files will get modified.  We don't modify vendor... using fileZilla, I transferred the files. Is there any way I could get this working without using composer?

**Comment by giacmir** [comment]
Hi @rvilama97 

composer is the suggested installation method. I suggest you tu use that. 

If you don't want to, or are unable to then you must install all the required dependencies listed in composer.json, and every sub-dependency listed in every dependency composer.json and so on.

You can have our module working this way, but composer is much simpler and much more reliable.
