### ISSUE TITLE
Recaptcha removed after initialization on custom page

### ISSUE THREAD

**Issue by danEsse** [magespecialist/m2-MSP_ReCaptcha#44]
### Preconditions

1. Magento 2.2.5
2. MSP_ReCaptcha v. 1.5.0

### Steps to reproduce

1. Created custom form page
2. Added layout update to embed recaptcha field
3. Moved to production mode

### Expected result

1. Recaptcha field shows in the form without being removed

### Actual result

1. The field appears and then disappears immediately

This is the layout
```
<container name="form.additional.info" label="Form Additional Info">
        <block class="MSP\ReCaptcha\Block\Frontend\ReCaptcha"
               name="msp-recaptcha"
               template="MSP_ReCaptcha::msp_recaptcha.phtml">
            <arguments>
                <argument name="jsLayout" xsi:type="array">
                    <item name="components" xsi:type="array">
                        <item name="msp-recaptcha" xsi:type="array">
                            <item name="component" xsi:type="string">MSP_ReCaptcha/js/reCaptcha</item>
                            <item name="zone" xsi:type="string">create</item>
                        </item>
                    </item>
                </argument>
            </arguments>
        </block>
</container>
```

This is the template
![image](https://user-images.githubusercontent.com/45855656/53803837-391d6880-3f46-11e9-83bc-dfea9f9be4cd.png)

In developer mode there's no problem, all works as expected, when I move Magento in production mode the field appears and disappears immediately.
I set the zone to "create" and enabled it in the backend configuration of the module.
In Magento default pages (contact, login, etc.) it all works fine.

**Comment by slackerzz** [comment]
This module has officially moved to the Magento2 github repo as part of Magento2 itself.

Please check here: https://github.com/magento/magespecialist_ReCaptcha/ .
