### ISSUE TITLE
Guest can checkout without reCaptcha

### ISSUE THREAD

**Issue by wasimhc** [magespecialist/m2-MSP_ReCaptcha#45]
Preconditions
1. Magento 2.2.7
2. MSP_ReCaptcha v. 1.5.0

Steps to reproduce
1. reCaptcha is not shown in guest checkout. 

Expected result
1. If we disable guest checkout (by setting Configuration >> SALES >> Checkout >> Checkout Options >> Allow Guest Checkout >> No), it works correctly. ReCaptcha should work in guest checkout (when Allow Guest Checkout >> Yes).  

Actual result
A guest can checkout without reCaptcha.

**Comment by slackerzz** [comment]
This module has officially moved to the Magento2 github repo as part of Magento2 itself.

Please check here: https://github.com/magento/magespecialist_ReCaptcha/ .
