### ISSUE TITLE
Cannot find the module in backend after installation

### ISSUE THREAD

**Issue by Kawazor** [magespecialist/m2-MSP_ReCaptcha#5]
I have uploaded the content of module's zip file in app/code/MSP/ReCaptcha directory, then installed it by command line with the following commands:

php bin/magento module:enable MSP_ReCaptcha
php bin/magento setup:upgrade

The problem is that now I don't see the module anywhere in my backend.

I have logged out and logged back in, cleared all the caches.

When I go in Stores/Configuration/Advanced/Advanced it shows that the MSP_ReCaptcha module is enabled.

Any help?

Thanks

**Comment by slackerzz** [comment]
Delete ```app/code/MSP```.
You need to install the module with composer as stated in the readme:

    composer require msp/recaptcha

and it will install all the dependencies needed to work.

**Comment by Nolwennig** [comment]
Hi,

I install the module with composer:

    composer require msp/recaptcha

and run

    php bin/magento setup:upgrade

The module work fine on localhost, but doesn 't work on production server. The admin menu doesn't appear end the captcha on frontend forms doesn't appear too.

Any help?

Thanks
