### ISSUE TITLE
Issue when checkout

### ISSUE THREAD

**Issue by thangmv** [magespecialist/m2-MSP_ReCaptcha#6]
Hi Phoenix,

I installed your module and thanks for great module but I got an issue when I checkout as guest. I input my email to and system report that "You already have an account with us. Sign in or continue as guest." then I input my password and click to signin but it always report that Wrong recaptcha. Please help me check this case.
Thanks,
Trent

**Comment by phoenix128** [comment]
Hello Trent,
thank you for reporting this issue. I confirm it is not working in that scenario. We are working to fix it ASAP.

**Comment by phoenix128** [comment]
Fixed it on version 1.0.3. Thank you for your report
