### ISSUE TITLE
Error Message when merge code

### ISSUE THREAD

**Issue by buituanbg** [magespecialist/m2-MSP_ReCaptcha#7]
Hi Team,

Thanks for sharing your extension. I got an issue as below:
1 - After merge code js it show error JS as below
`GET https://www.google.com/recaptcha/api.min.js 
req.load @ 83bc664….min.js:120
load @ 83bc664….min.js:112
require.s.contexts._.load @ 83bc664….min.js:134
load @ 83bc664….min.js:55
fetch @ 83bc664….min.js:55
check @ 83bc664….min.js:56
enable @ 83bc664….min.js:73
enable @ 83bc664….min.js:101
(anonymous) @ 83bc664….min.js:73
(anonymous) @ 83bc664….min.js:11
each @ 83bc664….min.js:3
enable @ 83bc664….min.js:71
init @ 83bc664….min.js:54
callGetModule @ 83bc664….min.js:74
completeLoad @ 83bc664….min.js:103
onScriptLoad @ 83bc664….min.js:112
83bc664….min.js:16

Uncaught Error: Script error for: https://www.google.com/recaptcha/api.js
http://requirejs.org/docs/errors.html#scripterror
    at makeError (83bc664….min.js:16)
    at HTMLScriptElement.onScriptError (83bc664….min.js:112)
makeError @ 83bc664….min.js:16
onScriptError @ 83bc664….min.js:112`
Then recaptcha box stop working. Please help me check this issue.

Thanks,
Kris

**Comment by phoenix128** [comment]
Are you on a default theme or a custom one?
What is your Magento version?

**Comment by buituanbg** [comment]
I used Custom theme is Porto and version is 2.1.7

**Comment by phoenix128** [comment]
Can you please try switching to default theme and see if it is working correctly? Just for a test.

**Comment by buituanbg** [comment]
I still get issue after switching to default theme. Strange.

**Comment by rbostan** [comment]
Hi, Thanks for extension.

Same issue in here v2.1.8
