### ISSUE TITLE
Add option to select which pages to add captcha to

### ISSUE THREAD

**Issue by Ghurdle** [magespecialist/m2-MSP_ReCaptcha#8]
I would like to only add the catpcha to the contact page and not any of the others but currently I am unable to achieve this, could you please direct me of how to achieve this if it is possible and if not is it something you plan on adding at any point? 

Many Thanks
George

**Comment by phoenix128** [comment]
Hello @Ghurdle ,
this is on our roadmap, we will release this very soon.

**Comment by phoenix128** [comment]
Hello @Ghurdle ,
please upgrade to 1.2.0, we just did it.
